from setuptools import setup

setup(
    name='espnfantasyapi',
    version='1.0',
    packages=['venv.lib.python3.7.site-packages.bs4', 'venv.lib.python3.7.site-packages.bs4.tests',
              'venv.lib.python3.7.site-packages.bs4.builder', 'venv.lib.python3.7.site-packages.idna',
              'venv.lib.python3.7.site-packages.pytz', 'venv.lib.python3.7.site-packages.boto3',
              'venv.lib.python3.7.site-packages.boto3.s3', 'venv.lib.python3.7.site-packages.boto3.ec2',
              'venv.lib.python3.7.site-packages.boto3.docs', 'venv.lib.python3.7.site-packages.boto3.dynamodb',
              'venv.lib.python3.7.site-packages.boto3.resources', 'venv.lib.python3.7.site-packages.click',
              'venv.lib.python3.7.site-packages.jinja2', 'venv.lib.python3.7.site-packages.certifi',
              'venv.lib.python3.7.site-packages.chardet', 'venv.lib.python3.7.site-packages.chardet.cli',
              'venv.lib.python3.7.site-packages.chardet.metadata', 'venv.lib.python3.7.site-packages.urllib3',
              'venv.lib.python3.7.site-packages.urllib3.util', 'venv.lib.python3.7.site-packages.urllib3.contrib',
              'venv.lib.python3.7.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.urllib3.packages',
              'venv.lib.python3.7.site-packages.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.botocore', 'venv.lib.python3.7.site-packages.botocore.docs',
              'venv.lib.python3.7.site-packages.botocore.docs.bcdoc',
              'venv.lib.python3.7.site-packages.botocore.retries', 'venv.lib.python3.7.site-packages.botocore.vendored',
              'venv.lib.python3.7.site-packages.botocore.vendored.requests',
              'venv.lib.python3.7.site-packages.botocore.vendored.requests.packages',
              'venv.lib.python3.7.site-packages.botocore.vendored.requests.packages.urllib3',
              'venv.lib.python3.7.site-packages.dateutil', 'venv.lib.python3.7.site-packages.dateutil.tz',
              'venv.lib.python3.7.site-packages.dateutil.parser', 'venv.lib.python3.7.site-packages.dateutil.zoneinfo',
              'venv.lib.python3.7.site-packages.gunicorn', 'venv.lib.python3.7.site-packages.gunicorn.app',
              'venv.lib.python3.7.site-packages.gunicorn.http', 'venv.lib.python3.7.site-packages.gunicorn.workers',
              'venv.lib.python3.7.site-packages.gunicorn.instrument', 'venv.lib.python3.7.site-packages.jmespath',
              'venv.lib.python3.7.site-packages.requests', 'venv.lib.python3.7.site-packages.werkzeug',
              'venv.lib.python3.7.site-packages.werkzeug.debug', 'venv.lib.python3.7.site-packages.werkzeug.wrappers',
              'venv.lib.python3.7.site-packages.werkzeug.middleware', 'venv.lib.python3.7.site-packages.soupsieve',
              'venv.lib.python3.7.site-packages.markupsafe', 'venv.lib.python3.7.site-packages.s3transfer',
              'venv.lib.python3.7.site-packages.itsdangerous',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations'],
    url='',
    license='',
    author='ianjpeck',
    author_email='',
    description=''
)
